const express = require("express");
const router = express.Router();

router.get("/", (req, res) => {
  res.json([
    {
      id: 1,
      name: "Lakme Lipstick",
      price: 299,
      category: "Lipstick",
      image: "/images/lakme lip.jpeg",
      rating:"4.8⭐⭐⭐⭐",
      description: "Long-lasting matte lipstick with rich color payoff and a smooth finish.",
      discount:"20% OFF",
    },
    {
      id: 2,
      name: "Maybelline Foundation",
      price: 799,
      category: "Foundation",
      image: "/images/maybe foun.jpeg",
      rating:"5.0⭐⭐⭐⭐⭐",
      description: "Lightweight liquid foundation that provides full coverage with a natural glow.",
    },
    {
      id: 3,
      name: "Mamaearth Face Wash",
      price: 299,
      category: "Face Wash",
      image: "/images/maear facewash.jpeg",
      rating:"3.8⭐⭐⭐",
      description: "Gentle face wash that deeply cleanses the skin and removes excess oil.",
      discount:"30% OFF",
    },
    {
      id: 4,
      name: "Mamaearth sunscreen",
      price: 399,
      category: "Foundation",
      image: "/images/sunscreen.jpeg",
      rating:"3.5⭐⭐⭐",
      description: "SPF 50 sunscreen that protects your skin from harmful UV rays without leaving a white cast.",
    },
    {
      id: 5,
      name: "Maybelline Lipstick",
      price: 399,
      category: "Lipstick",
      image: "/images/maybe lip.jpeg",
      rating:"4.2⭐⭐⭐⭐",
      description: "Creamy lipstick with vibrant color and long-lasting comfort.",
      discount:"10% OFF",
    },
    {
      id: 6,
      name: "Mars liquid Lipstick",
      price: 250,
      category: "Lipstick",
      image: "/images/mars lip.webp",
      rating:"3.9⭐⭐⭐",
      description: "Smudge-proof liquid lipstick with an ultra-matte finish.",
    },
    {
      id: 7,
      name: "Dazler Lipstick",
      price: 150,
      category: "Lipstick",
      image: "/images/daz lip.jpeg",
      rating:"3.2⭐⭐⭐",
      description: "Affordable lipstick offering rich pigmentation and soft texture.",
    },
    {
      id: 8,
      name: "Swiss Beauty Lipstick",
      price: 399,
      category: "Lipstick",
      image: "/images/swiss lip.webp",
      rating:"4.3⭐⭐⭐⭐",
      description: "Highly pigmented lipstick with a silky matte finish for everyday wear.",

    },
    {
      id: 9,
      name: "Revlon Lipstick",
      price: 520,
      category: "Lipstick",
      image: "/images/re lip.webp",
      rating:"5.0⭐⭐⭐⭐⭐",
      description: "Premium lipstick enriched with moisturizing ingredients for soft lips.",
      discount:"20% OFF",
    },
    {
      id: 10,
      name: " Sugar Lipstick",
      price: 690,
      category: "Lipstick",
      image: "/images/sugar lip.webp",
      rating:"2.5⭐⭐",
      description: "Transfer-proof matte lipstick with intense color and all-day wear.",
    },
    {
      id: 11,
      name: "Faces Canada Lipstick",
      price: 200,
      category: "Lipstick",
      image: "/images/face lip.jpeg",
      rating:"4.5⭐⭐⭐⭐",
      description: "Smooth and creamy lipstick that delivers rich color in a single swipe.",
      discount:"20% OFF",

    },
    {
      id: 12,
      name: "Nykaa Lipstick",
      price: 599,
      category: "Lipstick",
      image: "/images/nyka lip.jpeg",
      rating:"4.5⭐⭐⭐⭐",
      description: "Trendy lipstick collection with highly pigmented shades and a comfortable finish.",
      discount:"40% OFF",
    },
    {
      id: 13,
      name: " Lakme Foundation",
      price: 450,
      category: "Foundation",
      image: "/images/lakme foun.webp",
      rating:"4.2⭐⭐⭐⭐",
      description: "Lightweight foundation that blends easily for a flawless skin finish.",
    },
    {
      id: 14,
      name: " Huda Beauty Foundation",
      price: 1050,
      category: "Foundation",
      image: "/images/huda foun.webp",
      rating:"4.5⭐⭐⭐⭐",
      description: "High-performance foundation offering full coverage with a radiant finish.",
    },
    {
      id: 15,
      name: "Faces Canada Foundation",
      price: 559,
      category: "Foundation",
      image: "/images/face foun.webp",
      rating:"3.5⭐⭐⭐",
      description: "Buildable foundation that provides a smooth and natural-looking complexion.",
      discount:"10% OFF",
    },
    {
      id: 16,
      name: "Mac Foundation",
      price: 4000,
      category: "Foundation",
      image: "/images/mac foun.webp",
      rating:"5.0⭐⭐⭐⭐⭐",
      description: "Professional-quality foundation with long-lasting wear and flawless coverage.",
    },
    {
      id: 17,
      name: "Mamaearth Foundation",
      price: 250,
      category: "Foundation",
      image: "/images/ma foun.avif",
      rating:"2.8⭐⭐",
      description: "Skin-friendly foundation infused with natural ingredients for everyday use.",
      discount:"10% OFF",
    },
    {
      id: 18,
      name: " Colobar Foundation",
      price: 599,
      category: "Foundation",
      image: "/images/colo foun.jpeg",
      rating:"4.4⭐⭐⭐⭐",
      description: "Hydrating foundation that delivers medium to full coverage with a soft finish.",
    },
    {
      id: 19,
      name: "Nykaa Foundation",
      price: 799,
      category: "Foundation",
      image: "/images/ny foun.jpeg",
      rating:"5.0⭐⭐⭐⭐⭐",
      description: "Lightweight foundation that offers seamless blending and even skin tone.",
      discount:"50% OFF",
    },
    {
      id: 20,
      name: "Bobbi Brown Foundation",
      price: 450,
      category: "Foundation",
      image: "/images/bob foun.jpeg",
      rating:"3.4⭐⭐⭐",
      description: "Luxury foundation that provides natural-looking coverage with lasting comfort.",
    },
    {
      id: 21,
      name: "Cetaphil Face Wash",
      price: 850,
      category: "Face Wash",
      image: "/images/ceta wash.webp",
      rating:"4.2⭐⭐⭐⭐",
      description: "Dermatologist-recommended gentle cleanser suitable for sensitive skin.",
      discount:"40% OFF",
    },
    {
      id: 22,
      name: "Ponds Face Wash",
      price: 299,
      category: "Face Wash",
      image: "/images/pond wash.jpeg",
      rating:"4.6⭐⭐⭐⭐",
      description: "Refreshing face wash that removes dirt, oil, and impurities effectively.",
    },
    {
      id: 23,
      name: "Dermo co Face Wash",
      price: 259,
      category: "Face Wash",
      image: "/images/derma wash.webp",
      rating:"3.5⭐⭐⭐",
      description: "Salicylic acid face wash that helps reduce acne and controls excess oil.",
    },
    {
      id: 24,
      name: "Simple Face Wash",
      price: 199,
      category: "Face Wash",
      image: "/images/sim wash.jpeg",
      rating:"4.7⭐⭐⭐⭐",
      description: "Soap-free face wash made with skin-loving ingredients for gentle cleansing.",
      discount:"33% OFF",
    },
  ]);
});

module.exports = router;